export const packageSmokeConfigScript = [
    "import { defineConfig } from '@overkill-dev/test/config';",
    "import { defineReporter } from '@overkill-dev/engine';",
    '',
    'const packageSmokeReporter = defineReporter(function createPackageSmokeReporter() {',
    '    return {',
    '        dispose: null,',
    "        kind: 'real-time',",
    "        name: 'package-smoke',",
    '        onEvent() {},',
    '        onFinish: null,',
    "        sinks: [ { kind: 'memory' } ]",
    '    };',
    '});',
    '',
    'export const config = defineConfig({',
    '    reporters: [ packageSmokeReporter ],',
    '    profiles: {',
    '        microtest: {',
    "            testFamily: 'microtest',",
    '            execution: {',
    "                processModel: 'in-process',",
    "                scheduling: 'serial'",
    '            }',
    '        }',
    '    }',
    '});',
    ''
]
    .join('\n');

export const authoringSmokeScript = [
    "import { suite, test } from '@overkill-dev/test';",
    '',
    "export const testNode = suite('consumer root', [",
    '    suite({',
    "        title: 'nested',",
    "        metadata: { tags: [ 'smoke' ] },",
    '        children: [',
    '            test({',
    "                title: 'passes',",
    "                metadata: { tags: [ 'authoring' ] },",
    '                body(scope) {',
    '                    scope.assert.equal(1, 1);',
    '                    return scope.assert.collect();',
    '                }',
    '            })',
    '        ]',
    '    })',
    ']);',
    ''
]
    .join('\n');

export const rootImportScript = [
    "const testModule = await import('@overkill-dev/test');",
    'console.log(JSON.stringify(Object.keys(testModule)));',
    'console.log(String(testModule.defineConfig));',
    'console.log(String(testModule.orchestrator));',
    'console.log(String(testModule.createLineReporter));',
    'console.log(typeof testModule.testDouble);',
    'console.log(typeof testModule.doubleUsage.calledOnceWith);',
    'console.log(typeof testModule.rule.sequence);',
    'console.log(typeof testModule.testIterator);',
    "const loadValue = testModule.testDouble.returns('value');",
    "console.log(loadValue('id'));",
    'console.log(loadValue.callCount);',
    "const iterator = testModule.testIterator.yields([ 'created' ]);",
    'console.log(iterator.next().value);',
    'console.log(typeof testModule.test);',
    'console.log(typeof testModule.suite);',
    'const testNode = testModule.suite("smoke", [',
    '    testModule.test("passes", (scope) => {',
    '        scope.assert.true(true);',
    '        return scope.assert.collect();',
    '    })',
    ']);',
    'console.log(testNode.kind);',
    'console.log(testNode.children[0].kind);',
    'const tableNode = testModule.table({',
    "    title: 'rows',",
    '    cases: [1, 2],',
    '    test(scope) {',
    '        scope.assert.true(scope.parameters > 0);',
    '        return scope.assert.collect();',
    '    }',
    '});',
    'console.log(tableNode.kind);',
    'console.log(tableNode.cases.length);',
    'const facade = testModule.createTestFacade({',
    "    metadata: { extra: { from: 'facade' }, tags: [ 'facade' ] },",
    "    testFamily: 'integration'",
    '});',
    'console.log(JSON.stringify(Object.keys(facade)));',
    'const facadeNode = facade.suite({',
    "    title: 'facade smoke',",
    "    metadata: { tags: [ 'suite' ] },",
    '    children: [ facade.test({',
    "        title: 'facade passes',",
    "        metadata: { extra: { from: 'case' }, tags: [ 'case' ] },",
    '        body(scope) {',
    '            scope.assert.true(true);',
    '            return scope.assert.collect();',
    '        }',
    '    }) ]',
    '});',
    'console.log(facadeNode.metadata.kind);',
    'console.log(facadeNode.metadata.tags.join(","));',
    'console.log(facadeNode.children[0].metadata.kind);',
    'console.log(facadeNode.children[0].metadata.tags.join(","));',
    'console.log(facadeNode.children[0].metadata.extra.from);',
    'console.log(String(facade.doubleUsage));'
]
    .join('\n');

export const standardSubpathImportScript = [
    "const configModule = await import('@overkill-dev/test/config');",
    "const reportersModule = await import('@overkill-dev/test/reporters');",
    "const assertModule = await import('@overkill-dev/test/assert');",
    "const benchModule = await import('@overkill-dev/test/bench');",
    "const resourcesModule = await import('@overkill-dev/test/resources');",
    "const resourcesPackageModule = await import('@overkill-dev/resources');",
    "const baselinesModule = await import('@overkill-dev/test/baselines');",
    'console.log(JSON.stringify(Object.keys(configModule)));',
    'console.log(JSON.stringify(Object.keys(reportersModule)));',
    'console.log(JSON.stringify(Object.keys(assertModule)));',
    'console.log(JSON.stringify(Object.keys(resourcesModule)));',
    'console.log(typeof resourcesPackageModule.defineResource);',
    'console.log(configModule.defineConfig({ profiles: {} }).profiles === undefined);',
    'const context = {',
    '    relativizeLocationPath(location) {',
    '        return location.file;',
    '    }',
    '};',
    'console.log(reportersModule.createLineReporter()(context).name);',
    'console.log(reportersModule.createBriefReporter()(context).name);',
    'const dotReporter = reportersModule.createDotReporter()(context);',
    'console.log(dotReporter.name);',
    'if (dotReporter.dispose !== null) {',
    '    dotReporter.dispose();',
    '}',
    'const githubActionsOutputRenderer = reportersModule.createGithubActionsOutputRenderer()(context);',
    'console.log(githubActionsOutputRenderer.render({',
    "    annotation: null, kind: 'stdout-line', role: 'primary', text: 'hello'",
    '}));',
    'console.log(typeof assertModule.defineCompositeAssertion);',
    'const database = resourcesModule.defineResource({',
    "    name: 'database',",
    "    scope: 'per-case',",
    '    requirements: [],',
    '    dependencies: {},',
    '    acquire() {',
    '        return { url: "postgres://localhost" };',
    '    },',
    '    dispose: null',
    '});',
    'const runtime = resourcesModule.defineRuntime({',
    "    name: 'api',",
    '    dimensions: {},',
    '    resources: { database },',
    "    requirements: [ { kind: 'serial' } ]",
    '});',
    'console.log(database.name);',
    'console.log(runtime.id.name);',
    'console.log(Object.keys(runtime.resources).join(","));',
    'console.log(Object.isFrozen(database));',
    'console.log(Object.isFrozen(runtime));',
    'for (const [name, module] of [',
    "    [ 'bench', benchModule ],",
    "    [ 'baselines', baselinesModule ]",
    ']) {',
    '    console.log(JSON.stringify(Object.keys(module)));',
    '    try {',
    '        module.unavailable();',
    '    } catch (error) {',
    '        console.log(error instanceof Error ? error.message : String(error));',
    '    }',
    '}'
]
    .join('\n');

export const runConfigImportScript = [
    "const configModule = await import('@overkill-dev/run/config');",
    'console.log(JSON.stringify(Object.keys(configModule)));',
    'console.log(configModule.defineConfig({ profiles: {} }).profiles === undefined);',
    'console.log(typeof configModule.loadRunConfig);',
    "console.log(new configModule.RunConfigError('Invalid config.').name);"
]
    .join('\n');

const expectedRootExportNames = [
    'createTestFacade',
    'defineHarness',
    'defineMacro',
    'defineParameterizedTestBody',
    'doubleUsage',
    'rule',
    'runIfMain',
    'skippedTest',
    'suite',
    'table',
    'test',
    'testAsyncDisposable',
    'testAsyncIterable',
    'testAsyncIterator',
    'testDisposable',
    'testDouble',
    'testIterable',
    'testIterator'
];

export const expectedRootImportOutput = [
    JSON.stringify(expectedRootExportNames),
    'undefined',
    'undefined',
    'undefined',
    'function',
    'object',
    'function',
    'function',
    'value',
    '1',
    'created',
    'function',
    'function',
    'suite',
    'test',
    'table',
    '2',
    '["defineMacro","defineParameterizedTestBody","runIfMain","skippedTest","suite","table","test"]',
    'integration',
    'facade,suite',
    'integration',
    'facade,case',
    'case',
    'undefined',
    ''
]
    .join('\n');

export const expectedStandardSubpathImportOutput = [
    '["defineConfig"]',
    '["createBriefReporter","createDotReporter","createGithubActionsOutputRenderer","createLineReporter"]',
    '["defineCompositeAssertion","defineNarrowingCompositeAssertion"]',
    '["composeRuntimeContext","defineResource","defineRuntime","withRuntime"]',
    'function',
    'false',
    'line',
    'brief',
    'dot',
    'hello',
    'function',
    'database',
    'api',
    'database',
    'true',
    'true',
    '["unavailable"]',
    'The @overkill-dev/test/bench subpath is reserved until its leaf package exists.',
    '["unavailable"]',
    'The @overkill-dev/test/baselines subpath is reserved until its leaf package exists.',
    ''
]
    .join('\n');

export const expectedRunConfigImportOutput = [
    '["RunConfigError","defineConfig","loadRunConfig"]',
    'false',
    'function',
    'RunConfigError',
    ''
]
    .join('\n');
