name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Use Node.js from package.json
              uses: actions/setup-node@v6
              with:
                  node-version-file: package.json
            - name: Install dependencies
              run: npm ci
            - name: Check source code
              run: npx just lint
            - name: Compile source code
              run: npx just compile
            - name: Run unit tests
              run: npx just test-unit
